server:
  port: 8112
spring:
  application:
    name: student-service

word-config:
  wordIgnoreCase:
    - a
    - aboard
    - about
    - above
    - across
    - after
    - against
    - along
    - amid
    - among
    - an
    - and
    - anti
    - around
    - as
    - at
    - before
    - behind
    - below
    - beneath
    - beside
    - besides
    - between
    - beyond
    - but
    - by
    - concerning
    - considering
    - despite
    - down
    - during
    - except
    - excepting
    - excluding
    - following
    - for
    - from
    - in
    - inside
    - into
    - like
    - minus
    - near
    - of
    - off
    - on
    - onto
    - opposite
    - or
    - outside
    - over
    - past
    - per
    - plus
    - regarding
    - round
    - save
    - since
    - so
    - than
    - the
    - through
    - to
    - toward
    - towards
    - under
    - underneath
    - unlike
    - until
    - up
    - upon
    - versus
    - via
    - with
    - within
    - without
    - yet

management:
  endpoints:
    web:
      exposure:
        include: "health"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://mysqldb/student-manager
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto:
    show-sql: true
    generate-ddl: true
